version: "3.8"
services:
  app:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./data
        target: /app/data
